### ISSUE TITLE
Is there any way to add a label to my issues, by adding a text or a tag of some sort to the email?

### ISSUE THREAD

**Issue by simoncat42** [FundersClub/fire#422]
This is a feature request.
I'd like to be able to do this in an email to firebot.

`@firebot:label:<mylabelname>

And have it automatically create the label in github. This way I can search for all the issues created this way.

Thanks! Love the service already.

**Comment by eranrund** [comment]
Sorry, unfortunately in order to manipulate tags we would need to ask for write access to the repository. We only ask for read-only access, which does not let you manipulate tags. You should be able to search for all issues opened by the bot (for example: https://github.com/FundersClub/fire-test/issues/created_by/fire-bot)

I hope this helps!

**Comment by simoncat42** [comment]
Thanks for the answer! Very sensible. That searching for issues created by
firebot will do the trick for now.

**Comment by JFQueralt** [comment]
I was looking for the same and the rationale that makes it impossible is sensible and reasonable.

One solution could be:
- Fire-bot creates the Issue
- An Action detects Issues created by Fire-bot and sets the corresponding labels and other necessary default settings.
This should work:
https://github.com/marketplace/actions/auto-label

Great job with the bot, @simoncat42 .
