### ISSUE TITLE
Bug (?): Issue created via email is not assigned to a team member

### ISSUE THREAD

**Issue by steffenkrogmann** [FundersClub/fire#426]
I set up 3 GitHub handles and email addresses in the "Team" section in the Fire settings.

When i send an email, an issue is created, but it is not assigned to anyone.

I expected it to be assigned to the team members that I specified in the settings.

**Comment by eranrund** [comment]
@steffenkrogmann Firebot does not automatically assign issues to users. The team emails map only affects whether the user gets mentioned in the issue. By default firebot would put at the top of the issue a line that says `Sent by Some Name (email@test.com). Created by Fire`, where Some Name/email@test.com are the sender details. If the email address matches an entry in the team map, the relevant user would get tagged.

Assigning issues to specific users require having a write permission to the repository, so that is not currently possible.
